name: Annotate CI run with test results
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
jobs:
  annotate:
    name: Annotate CI run with test results
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    strategy:
       fail-fast: false
       matrix:
          os:
            - { prettyName: Windows }
            - { prettyName: macOS }
            - { prettyName: Linux }
    timeout-minutes: 5
    steps:
      - name: Annotate CI run with test results
        uses: dorny/test-reporter@v1.4.2
        with:
          artifact: libyambar-test-results-${{matrix.os.prettyName}}
          name: Test Results on ${{matrix.os.prettyName}}
          path: "*.trx"
          reporter: dotnet-trx
          list-suites: 'failed'
          list-tests: 'failed'
